### ISSUE TITLE
Tunnel curve

### ISSUE THREAD

**Issue by yucolabjames** [keijiro/KvantTunnel#3]
Hello there, does anyone know how to make the tunnel turn to the left/ right?

**Comment by keijiro** [comment]
Sorry it isn't supported.

**Comment by yucolabjames** [comment]
No worries :) we purchased a commercial version of your work in the Unity assets stored.  It came with curved tunnel support. Amazing work @keijiro! really appreciate your contributions!

**Comment by keijiro** [comment]
I have never sold any assets in Unity Asset Store. Which one did you bought? Although it's okay to sell my asset via Asset Store (it's not prohibited), I'm just curious how it's sold.

**Comment by yucolabjames** [comment]
It's part of a package called **Curved Word**. Pretty neat actually.
https://youtu.be/5AGeZEQ3H4E?t=24
https://assetstore.unity.com/packages/vfx/shaders/curved-world-26165

![image](https://user-images.githubusercontent.com/40826198/68178414-e6111f00-ffc6-11e9-8d65-344045aa136c.png)

**Comment by keijiro** [comment]
Thank you for the information.
